#!/usr/bin/env perl

use strict;
use warnings;

use Getopt::Long::Descriptive;
use List::Util qw/ min max /;

my ( $opt, $usage ) = describe_options(
	'usage: %c %o value1 value2 ... valueN',
	[ 'help|h' => 'Print usage and help text' ],
);

if ( $opt->{help} ) {
	print $usage->text;
	exit;
}

my @ticks = qw/ ▁ ▂ ▃ ▄ ▅ ▆ ▇ █ /;

my @values = @ARGV;

my $min   = min @values;
my $max   = max @values;
my $range = $max - $min;
my $size  = ($range << 8) / (scalar @ticks - 1);

$size = 1 if $size < 1;

for my $v ( @values ) {
	my $v_size = (($v - $min) << 8) / $size;

	print $ticks[$v_size];
}

print "\n";

